feat: Enhance destroy workflow by adding S3 bucket name retrieval and validation before emptying

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -86,13 +86,28 @@ jobs:
           echo "Uploading files from src/ to s3://${AWS_S3_BUCKET_NAME}/"
           aws s3 sync src/ s3://${AWS_S3_BUCKET_NAME}/ --delete
 
-      # This step is only executed if the destroy flag is set to true
-      - name: Empty S3 Bucket Before Destroy
-        if: steps.read-destroy-config.outputs.destroy == 'true'
+      # Only run the following steps if the destroy flag is set to true
+      - name: Get S3 Bucket Name for Destroy
+        id: get-s3-bucket-name-destroy
+        if: steps.read-destroy-config.outputs.destroy == 'true' && steps.terraform-init-step.conclusion == 'success'
         run: |
-          # This step will empty the S3 bucket before destroying the infrastructure
-          AWS_S3_BUCKET_NAME=$(terraform -chdir=infra output -raw s3_static_site_bucket_name)
+          S3_BUCKET_NAME=$(terraform -chdir=infra output -raw s3_static_site_bucket_name)
+          echo "s3_bucket_name_for_destroy=$S3_BUCKET_NAME" >> $GITHUB_OUTPUT # Usar um nome de output exclusivo
+
+      # Empty S3 Bucket Before Destroy
+      - name: Empty S3 Bucket Before Destroy
+        id: empty-s3-bucket-before-destroy
+        if: steps.read-destroy-config.outputs.destroy == 'true' && steps.get-s3-bucket-name-destroy.conclusion == 'success'
+        run: |
+          # use output 'get-s3-bucket-name-destroy'
+          AWS_S3_BUCKET_NAME=${{ steps.get-s3-bucket-name-destroy.outputs.s3_bucket_name_for_destroy }}
           echo "Attempting to empty s3://${AWS_S3_BUCKET_NAME} before destroy..."
+
+          # Check if the bucket name is set
+          if [ -z "${AWS_S3_BUCKET_NAME}" ]; then
+            echo "Error: S3 bucket name could not be determined. Aborting bucket empty process."
+            exit 1
+          fi
 
           # list and delete ALL object versions in the bucket
           aws s3api list-object-versions --bucket "${AWS_S3_BUCKET_NAME}" | \
